# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'manual_volt_control.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QDoubleSpinBox, QLabel,
    QPushButton, QSizePolicy, QWidget)
import buttons_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(445, 371)
        self.r8EnableBtn = QPushButton(Dialog)
        self.r8EnableBtn.setObjectName(u"r8EnableBtn")
        self.r8EnableBtn.setEnabled(True)
        self.r8EnableBtn.setGeometry(QRect(261, 308, 44, 35))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r8EnableBtn.sizePolicy().hasHeightForWidth())
        self.r8EnableBtn.setSizePolicy(sizePolicy)
        self.r8EnableBtn.setMinimumSize(QSize(41, 21))
        self.r8EnableBtn.setBaseSize(QSize(41, 21))
        self.r8EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        icon = QIcon()
        icon.addFile(u":/toggle/off", QSize(), QIcon.Normal, QIcon.Off)
        icon.addFile(u":/toggle/on", QSize(), QIcon.Normal, QIcon.On)
        self.r8EnableBtn.setIcon(icon)
        self.r8EnableBtn.setIconSize(QSize(40, 40))
        self.r8EnableBtn.setCheckable(True)
        self.r8EnableBtn.setChecked(False)
        self.label_17 = QLabel(Dialog)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(237, 308, 20, 35))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy1)
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_12 = QLabel(Dialog)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(237, 105, 20, 35))
        sizePolicy1.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy1)
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_15 = QLabel(Dialog)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(237, 227, 20, 35))
        sizePolicy1.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy1)
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.r7EnableBtn = QPushButton(Dialog)
        self.r7EnableBtn.setObjectName(u"r7EnableBtn")
        self.r7EnableBtn.setEnabled(True)
        self.r7EnableBtn.setGeometry(QRect(261, 268, 44, 34))
        sizePolicy.setHeightForWidth(self.r7EnableBtn.sizePolicy().hasHeightForWidth())
        self.r7EnableBtn.setSizePolicy(sizePolicy)
        self.r7EnableBtn.setMinimumSize(QSize(41, 21))
        self.r7EnableBtn.setBaseSize(QSize(41, 21))
        self.r7EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.r7EnableBtn.setIcon(icon)
        self.r7EnableBtn.setIconSize(QSize(40, 40))
        self.r7EnableBtn.setCheckable(True)
        self.r7EnableBtn.setChecked(False)
        self.label_13 = QLabel(Dialog)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(237, 146, 20, 35))
        sizePolicy1.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy1)
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.r2SpinBox = QDoubleSpinBox(Dialog)
        self.r2SpinBox.setObjectName(u"r2SpinBox")
        self.r2SpinBox.setGeometry(QRect(311, 69, 111, 26))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(100)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.r2SpinBox.sizePolicy().hasHeightForWidth())
        self.r2SpinBox.setSizePolicy(sizePolicy2)
        self.r2SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.r2SpinBox.setMinimum(-10.000000000000000)
        self.r2SpinBox.setMaximum(10.000000000000000)
        self.r5SpinBox = QDoubleSpinBox(Dialog)
        self.r5SpinBox.setObjectName(u"r5SpinBox")
        self.r5SpinBox.setGeometry(QRect(311, 190, 111, 26))
        sizePolicy2.setHeightForWidth(self.r5SpinBox.sizePolicy().hasHeightForWidth())
        self.r5SpinBox.setSizePolicy(sizePolicy2)
        self.r5SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.r5SpinBox.setMinimum(-10.000000000000000)
        self.r5SpinBox.setMaximum(10.000000000000000)
        self.r3EnableBtn = QPushButton(Dialog)
        self.r3EnableBtn.setObjectName(u"r3EnableBtn")
        self.r3EnableBtn.setEnabled(True)
        self.r3EnableBtn.setGeometry(QRect(261, 105, 44, 35))
        sizePolicy.setHeightForWidth(self.r3EnableBtn.sizePolicy().hasHeightForWidth())
        self.r3EnableBtn.setSizePolicy(sizePolicy)
        self.r3EnableBtn.setMinimumSize(QSize(41, 21))
        self.r3EnableBtn.setBaseSize(QSize(41, 21))
        self.r3EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.r3EnableBtn.setIcon(icon)
        self.r3EnableBtn.setIconSize(QSize(40, 40))
        self.r3EnableBtn.setCheckable(True)
        self.r3EnableBtn.setChecked(False)
        self.label_16 = QLabel(Dialog)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(237, 268, 20, 35))
        sizePolicy1.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy1)
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_10 = QLabel(Dialog)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(237, 24, 20, 35))
        sizePolicy1.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy1)
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.r6SpinBox = QDoubleSpinBox(Dialog)
        self.r6SpinBox.setObjectName(u"r6SpinBox")
        self.r6SpinBox.setGeometry(QRect(311, 231, 111, 26))
        sizePolicy2.setHeightForWidth(self.r6SpinBox.sizePolicy().hasHeightForWidth())
        self.r6SpinBox.setSizePolicy(sizePolicy2)
        self.r6SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.r6SpinBox.setMinimum(-10.000000000000000)
        self.r6SpinBox.setMaximum(10.000000000000000)
        self.r3SpinBox = QDoubleSpinBox(Dialog)
        self.r3SpinBox.setObjectName(u"r3SpinBox")
        self.r3SpinBox.setGeometry(QRect(311, 109, 111, 26))
        sizePolicy2.setHeightForWidth(self.r3SpinBox.sizePolicy().hasHeightForWidth())
        self.r3SpinBox.setSizePolicy(sizePolicy2)
        self.r3SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.r3SpinBox.setMinimum(-10.000000000000000)
        self.r3SpinBox.setMaximum(10.000000000000000)
        self.r1EnableBtn = QPushButton(Dialog)
        self.r1EnableBtn.setObjectName(u"r1EnableBtn")
        self.r1EnableBtn.setEnabled(True)
        self.r1EnableBtn.setGeometry(QRect(261, 24, 44, 35))
        sizePolicy.setHeightForWidth(self.r1EnableBtn.sizePolicy().hasHeightForWidth())
        self.r1EnableBtn.setSizePolicy(sizePolicy)
        self.r1EnableBtn.setMinimumSize(QSize(41, 21))
        self.r1EnableBtn.setBaseSize(QSize(41, 21))
        self.r1EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.r1EnableBtn.setIcon(icon)
        self.r1EnableBtn.setIconSize(QSize(40, 40))
        self.r1EnableBtn.setCheckable(True)
        self.r1EnableBtn.setChecked(False)
        self.r6EnableBtn = QPushButton(Dialog)
        self.r6EnableBtn.setObjectName(u"r6EnableBtn")
        self.r6EnableBtn.setEnabled(True)
        self.r6EnableBtn.setGeometry(QRect(261, 227, 44, 35))
        sizePolicy.setHeightForWidth(self.r6EnableBtn.sizePolicy().hasHeightForWidth())
        self.r6EnableBtn.setSizePolicy(sizePolicy)
        self.r6EnableBtn.setMinimumSize(QSize(41, 21))
        self.r6EnableBtn.setBaseSize(QSize(41, 21))
        self.r6EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.r6EnableBtn.setIcon(icon)
        self.r6EnableBtn.setIconSize(QSize(40, 40))
        self.r6EnableBtn.setCheckable(True)
        self.r6EnableBtn.setChecked(False)
        self.r1SpinBox = QDoubleSpinBox(Dialog)
        self.r1SpinBox.setObjectName(u"r1SpinBox")
        self.r1SpinBox.setGeometry(QRect(311, 28, 111, 26))
        sizePolicy2.setHeightForWidth(self.r1SpinBox.sizePolicy().hasHeightForWidth())
        self.r1SpinBox.setSizePolicy(sizePolicy2)
        self.r1SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.r1SpinBox.setMinimum(-10.000000000000000)
        self.r1SpinBox.setMaximum(10.000000000000000)
        self.label_11 = QLabel(Dialog)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(237, 65, 20, 35))
        sizePolicy1.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy1)
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.r4EnableBtn = QPushButton(Dialog)
        self.r4EnableBtn.setObjectName(u"r4EnableBtn")
        self.r4EnableBtn.setEnabled(True)
        self.r4EnableBtn.setGeometry(QRect(261, 146, 44, 34))
        sizePolicy.setHeightForWidth(self.r4EnableBtn.sizePolicy().hasHeightForWidth())
        self.r4EnableBtn.setSizePolicy(sizePolicy)
        self.r4EnableBtn.setMinimumSize(QSize(41, 21))
        self.r4EnableBtn.setBaseSize(QSize(41, 21))
        self.r4EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.r4EnableBtn.setIcon(icon)
        self.r4EnableBtn.setIconSize(QSize(40, 40))
        self.r4EnableBtn.setCheckable(True)
        self.r4EnableBtn.setChecked(False)
        self.r4SpinBox = QDoubleSpinBox(Dialog)
        self.r4SpinBox.setObjectName(u"r4SpinBox")
        self.r4SpinBox.setGeometry(QRect(311, 150, 111, 26))
        sizePolicy2.setHeightForWidth(self.r4SpinBox.sizePolicy().hasHeightForWidth())
        self.r4SpinBox.setSizePolicy(sizePolicy2)
        self.r4SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.r4SpinBox.setMinimum(-10.000000000000000)
        self.r4SpinBox.setMaximum(10.000000000000000)
        self.r8SpinBox = QDoubleSpinBox(Dialog)
        self.r8SpinBox.setObjectName(u"r8SpinBox")
        self.r8SpinBox.setGeometry(QRect(311, 313, 111, 26))
        sizePolicy2.setHeightForWidth(self.r8SpinBox.sizePolicy().hasHeightForWidth())
        self.r8SpinBox.setSizePolicy(sizePolicy2)
        self.r8SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.r8SpinBox.setMinimum(-10.000000000000000)
        self.r8SpinBox.setMaximum(10.000000000000000)
        self.r2EnableBtn = QPushButton(Dialog)
        self.r2EnableBtn.setObjectName(u"r2EnableBtn")
        self.r2EnableBtn.setEnabled(True)
        self.r2EnableBtn.setGeometry(QRect(261, 65, 44, 34))
        sizePolicy.setHeightForWidth(self.r2EnableBtn.sizePolicy().hasHeightForWidth())
        self.r2EnableBtn.setSizePolicy(sizePolicy)
        self.r2EnableBtn.setMinimumSize(QSize(41, 21))
        self.r2EnableBtn.setBaseSize(QSize(41, 21))
        self.r2EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.r2EnableBtn.setIcon(icon)
        self.r2EnableBtn.setIconSize(QSize(40, 40))
        self.r2EnableBtn.setCheckable(True)
        self.r2EnableBtn.setChecked(False)
        self.r7SpinBox = QDoubleSpinBox(Dialog)
        self.r7SpinBox.setObjectName(u"r7SpinBox")
        self.r7SpinBox.setGeometry(QRect(311, 272, 111, 26))
        sizePolicy2.setHeightForWidth(self.r7SpinBox.sizePolicy().hasHeightForWidth())
        self.r7SpinBox.setSizePolicy(sizePolicy2)
        self.r7SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.r7SpinBox.setMinimum(-10.000000000000000)
        self.r7SpinBox.setMaximum(10.000000000000000)
        self.label_14 = QLabel(Dialog)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(237, 186, 20, 35))
        sizePolicy1.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy1)
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.r5EnableBtn = QPushButton(Dialog)
        self.r5EnableBtn.setObjectName(u"r5EnableBtn")
        self.r5EnableBtn.setEnabled(True)
        self.r5EnableBtn.setGeometry(QRect(261, 186, 44, 35))
        sizePolicy.setHeightForWidth(self.r5EnableBtn.sizePolicy().hasHeightForWidth())
        self.r5EnableBtn.setSizePolicy(sizePolicy)
        self.r5EnableBtn.setMinimumSize(QSize(41, 21))
        self.r5EnableBtn.setBaseSize(QSize(41, 21))
        self.r5EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.r5EnableBtn.setIcon(icon)
        self.r5EnableBtn.setIconSize(QSize(40, 40))
        self.r5EnableBtn.setCheckable(True)
        self.r5EnableBtn.setChecked(False)
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(17, 24, 17, 35))
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.l4EnableBtn = QPushButton(Dialog)
        self.l4EnableBtn.setObjectName(u"l4EnableBtn")
        self.l4EnableBtn.setEnabled(True)
        self.l4EnableBtn.setGeometry(QRect(40, 146, 44, 34))
        sizePolicy.setHeightForWidth(self.l4EnableBtn.sizePolicy().hasHeightForWidth())
        self.l4EnableBtn.setSizePolicy(sizePolicy)
        self.l4EnableBtn.setMinimumSize(QSize(41, 21))
        self.l4EnableBtn.setBaseSize(QSize(41, 21))
        self.l4EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.l4EnableBtn.setIcon(icon)
        self.l4EnableBtn.setIconSize(QSize(40, 40))
        self.l4EnableBtn.setCheckable(True)
        self.l4EnableBtn.setChecked(False)
        self.l2SpinBox = QDoubleSpinBox(Dialog)
        self.l2SpinBox.setObjectName(u"l2SpinBox")
        self.l2SpinBox.setGeometry(QRect(90, 69, 111, 26))
        sizePolicy2.setHeightForWidth(self.l2SpinBox.sizePolicy().hasHeightForWidth())
        self.l2SpinBox.setSizePolicy(sizePolicy2)
        self.l2SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.l2SpinBox.setMinimum(-10.000000000000000)
        self.label_8 = QLabel(Dialog)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(17, 308, 17, 35))
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.l7EnableBtn = QPushButton(Dialog)
        self.l7EnableBtn.setObjectName(u"l7EnableBtn")
        self.l7EnableBtn.setEnabled(True)
        self.l7EnableBtn.setGeometry(QRect(40, 268, 44, 34))
        sizePolicy.setHeightForWidth(self.l7EnableBtn.sizePolicy().hasHeightForWidth())
        self.l7EnableBtn.setSizePolicy(sizePolicy)
        self.l7EnableBtn.setMinimumSize(QSize(41, 21))
        self.l7EnableBtn.setBaseSize(QSize(41, 21))
        self.l7EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.l7EnableBtn.setIcon(icon)
        self.l7EnableBtn.setIconSize(QSize(40, 40))
        self.l7EnableBtn.setCheckable(True)
        self.l7EnableBtn.setChecked(False)
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(17, 65, 17, 35))
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_6 = QLabel(Dialog)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(17, 227, 17, 35))
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.l2EnableBtn = QPushButton(Dialog)
        self.l2EnableBtn.setObjectName(u"l2EnableBtn")
        self.l2EnableBtn.setEnabled(True)
        self.l2EnableBtn.setGeometry(QRect(40, 65, 44, 34))
        sizePolicy.setHeightForWidth(self.l2EnableBtn.sizePolicy().hasHeightForWidth())
        self.l2EnableBtn.setSizePolicy(sizePolicy)
        self.l2EnableBtn.setMinimumSize(QSize(41, 21))
        self.l2EnableBtn.setBaseSize(QSize(41, 21))
        self.l2EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.l2EnableBtn.setIcon(icon)
        self.l2EnableBtn.setIconSize(QSize(40, 40))
        self.l2EnableBtn.setCheckable(True)
        self.l2EnableBtn.setChecked(False)
        self.l6SpinBox = QDoubleSpinBox(Dialog)
        self.l6SpinBox.setObjectName(u"l6SpinBox")
        self.l6SpinBox.setGeometry(QRect(90, 231, 111, 26))
        sizePolicy2.setHeightForWidth(self.l6SpinBox.sizePolicy().hasHeightForWidth())
        self.l6SpinBox.setSizePolicy(sizePolicy2)
        self.l6SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.l6SpinBox.setMinimum(-10.000000000000000)
        self.l5EnableBtn = QPushButton(Dialog)
        self.l5EnableBtn.setObjectName(u"l5EnableBtn")
        self.l5EnableBtn.setEnabled(True)
        self.l5EnableBtn.setGeometry(QRect(40, 186, 44, 35))
        sizePolicy.setHeightForWidth(self.l5EnableBtn.sizePolicy().hasHeightForWidth())
        self.l5EnableBtn.setSizePolicy(sizePolicy)
        self.l5EnableBtn.setMinimumSize(QSize(41, 21))
        self.l5EnableBtn.setBaseSize(QSize(41, 21))
        self.l5EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.l5EnableBtn.setIcon(icon)
        self.l5EnableBtn.setIconSize(QSize(40, 40))
        self.l5EnableBtn.setCheckable(True)
        self.l5EnableBtn.setChecked(False)
        self.l7SpinBox = QDoubleSpinBox(Dialog)
        self.l7SpinBox.setObjectName(u"l7SpinBox")
        self.l7SpinBox.setGeometry(QRect(90, 272, 111, 26))
        sizePolicy2.setHeightForWidth(self.l7SpinBox.sizePolicy().hasHeightForWidth())
        self.l7SpinBox.setSizePolicy(sizePolicy2)
        self.l7SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.l7SpinBox.setMinimum(-10.000000000000000)
        self.label_4 = QLabel(Dialog)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(17, 146, 17, 35))
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.l8SpinBox = QDoubleSpinBox(Dialog)
        self.l8SpinBox.setObjectName(u"l8SpinBox")
        self.l8SpinBox.setGeometry(QRect(90, 312, 111, 26))
        sizePolicy2.setHeightForWidth(self.l8SpinBox.sizePolicy().hasHeightForWidth())
        self.l8SpinBox.setSizePolicy(sizePolicy2)
        self.l8SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.l8SpinBox.setMinimum(-10.000000000000000)
        self.l1SpinBox = QDoubleSpinBox(Dialog)
        self.l1SpinBox.setObjectName(u"l1SpinBox")
        self.l1SpinBox.setGeometry(QRect(90, 28, 111, 26))
        sizePolicy2.setHeightForWidth(self.l1SpinBox.sizePolicy().hasHeightForWidth())
        self.l1SpinBox.setSizePolicy(sizePolicy2)
        self.l1SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.l1SpinBox.setMinimum(-10.000000000000000)
        self.l3SpinBox = QDoubleSpinBox(Dialog)
        self.l3SpinBox.setObjectName(u"l3SpinBox")
        self.l3SpinBox.setGeometry(QRect(90, 109, 111, 26))
        sizePolicy2.setHeightForWidth(self.l3SpinBox.sizePolicy().hasHeightForWidth())
        self.l3SpinBox.setSizePolicy(sizePolicy2)
        self.l3SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.l3SpinBox.setMinimum(-10.000000000000000)
        self.label_5 = QLabel(Dialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(17, 186, 17, 35))
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.l5SpinBox = QDoubleSpinBox(Dialog)
        self.l5SpinBox.setObjectName(u"l5SpinBox")
        self.l5SpinBox.setGeometry(QRect(90, 190, 111, 26))
        sizePolicy2.setHeightForWidth(self.l5SpinBox.sizePolicy().hasHeightForWidth())
        self.l5SpinBox.setSizePolicy(sizePolicy2)
        self.l5SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.l5SpinBox.setMinimum(-10.000000000000000)
        self.label_7 = QLabel(Dialog)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(17, 268, 17, 35))
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.l6EnableBtn = QPushButton(Dialog)
        self.l6EnableBtn.setObjectName(u"l6EnableBtn")
        self.l6EnableBtn.setEnabled(True)
        self.l6EnableBtn.setGeometry(QRect(40, 227, 44, 35))
        sizePolicy.setHeightForWidth(self.l6EnableBtn.sizePolicy().hasHeightForWidth())
        self.l6EnableBtn.setSizePolicy(sizePolicy)
        self.l6EnableBtn.setMinimumSize(QSize(41, 21))
        self.l6EnableBtn.setBaseSize(QSize(41, 21))
        self.l6EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.l6EnableBtn.setIcon(icon)
        self.l6EnableBtn.setIconSize(QSize(40, 40))
        self.l6EnableBtn.setCheckable(True)
        self.l6EnableBtn.setChecked(False)
        self.l1EnableBtn = QPushButton(Dialog)
        self.l1EnableBtn.setObjectName(u"l1EnableBtn")
        self.l1EnableBtn.setEnabled(True)
        self.l1EnableBtn.setGeometry(QRect(40, 24, 44, 35))
        sizePolicy.setHeightForWidth(self.l1EnableBtn.sizePolicy().hasHeightForWidth())
        self.l1EnableBtn.setSizePolicy(sizePolicy)
        self.l1EnableBtn.setMinimumSize(QSize(41, 21))
        self.l1EnableBtn.setBaseSize(QSize(41, 21))
        self.l1EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.l1EnableBtn.setIcon(icon)
        self.l1EnableBtn.setIconSize(QSize(40, 40))
        self.l1EnableBtn.setCheckable(True)
        self.l1EnableBtn.setChecked(False)
        self.l8EnableBtn = QPushButton(Dialog)
        self.l8EnableBtn.setObjectName(u"l8EnableBtn")
        self.l8EnableBtn.setEnabled(True)
        self.l8EnableBtn.setGeometry(QRect(40, 308, 44, 35))
        sizePolicy.setHeightForWidth(self.l8EnableBtn.sizePolicy().hasHeightForWidth())
        self.l8EnableBtn.setSizePolicy(sizePolicy)
        self.l8EnableBtn.setMinimumSize(QSize(41, 21))
        self.l8EnableBtn.setBaseSize(QSize(41, 21))
        self.l8EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.l8EnableBtn.setIcon(icon)
        self.l8EnableBtn.setIconSize(QSize(40, 40))
        self.l8EnableBtn.setCheckable(True)
        self.l8EnableBtn.setChecked(False)
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(17, 105, 17, 35))
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.l3EnableBtn = QPushButton(Dialog)
        self.l3EnableBtn.setObjectName(u"l3EnableBtn")
        self.l3EnableBtn.setEnabled(True)
        self.l3EnableBtn.setGeometry(QRect(40, 105, 44, 35))
        sizePolicy.setHeightForWidth(self.l3EnableBtn.sizePolicy().hasHeightForWidth())
        self.l3EnableBtn.setSizePolicy(sizePolicy)
        self.l3EnableBtn.setMinimumSize(QSize(41, 21))
        self.l3EnableBtn.setBaseSize(QSize(41, 21))
        self.l3EnableBtn.setStyleSheet(u"QPushButton{\n"
"	background-color: none;\n"
"	border-radius: 5%;\n"
"}")
        self.l3EnableBtn.setIcon(icon)
        self.l3EnableBtn.setIconSize(QSize(40, 40))
        self.l3EnableBtn.setCheckable(True)
        self.l3EnableBtn.setChecked(False)
        self.l4SpinBox = QDoubleSpinBox(Dialog)
        self.l4SpinBox.setObjectName(u"l4SpinBox")
        self.l4SpinBox.setGeometry(QRect(90, 150, 111, 26))
        sizePolicy2.setHeightForWidth(self.l4SpinBox.sizePolicy().hasHeightForWidth())
        self.l4SpinBox.setSizePolicy(sizePolicy2)
        self.l4SpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.l4SpinBox.setMinimum(-10.000000000000000)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.r8EnableBtn.setText("")
        self.label_17.setText(QCoreApplication.translate("Dialog", u"R8", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"R3", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"R6", None))
        self.r7EnableBtn.setText("")
        self.label_13.setText(QCoreApplication.translate("Dialog", u"R4", None))
        self.r2SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.r5SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.r3EnableBtn.setText("")
        self.label_16.setText(QCoreApplication.translate("Dialog", u"R7", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"R1", None))
        self.r6SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.r3SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.r1EnableBtn.setText("")
        self.r6EnableBtn.setText("")
        self.r1SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"R2", None))
        self.r4EnableBtn.setText("")
        self.r4SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.r8SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.r2EnableBtn.setText("")
        self.r7SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"R5", None))
        self.r5EnableBtn.setText("")
        self.label.setText(QCoreApplication.translate("Dialog", u"L1", None))
        self.l4EnableBtn.setText("")
        self.l2SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"L8", None))
        self.l7EnableBtn.setText("")
        self.label_2.setText(QCoreApplication.translate("Dialog", u"L2", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"L6", None))
        self.l2EnableBtn.setText("")
        self.l6SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.l5EnableBtn.setText("")
        self.l7SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"L4", None))
        self.l8SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.l1SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.l3SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"L5", None))
        self.l5SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"L7", None))
        self.l6EnableBtn.setText("")
        self.l1EnableBtn.setText("")
        self.l8EnableBtn.setText("")
        self.label_3.setText(QCoreApplication.translate("Dialog", u"L3", None))
        self.l3EnableBtn.setText("")
        self.l4SpinBox.setSuffix(QCoreApplication.translate("Dialog", u" V", None))
    # retranslateUi

